### ISSUE TITLE
event.decodeResults throwing compile time error due to results.topics String? is nullable

### ISSUE THREAD

**Issue by bobwith2bees** [inveker/web3dart_builders#10]
Upgrading pubspec to  http 1.1 and web3dart 2.7.0, the abi generated code appears to be incompatible with the changes in http

```dart
      final decoded = event.decodeResults(
        result.topics!,
        result.data!,
      );
```

The result.topics line has the following error when the app is compiled (the IDE linter is not complaining) : 
`Error:` The argument type 'List<String?>' can't be assigned to the parameter type 'List<String>' because 'String?' is nullable and 'String' isn't.

```
dependencies:
  http: ^1.1.0 
  web3dart: ^2.7.0

dev_dependencies:
  web3dart_builders: ^0.0.7 
```

That's as far as I have gotten.   (i.e. if this is an issue with an upstream dependency of web3dart_builders included package or not.).
